version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo "Instalando dependencias..."
      - npm install
  build:
    commands:
      - echo "Ejecutando pruebas en paralelo..."
      - npm run cy:parallel || echo "Falló el comando cy:parallel"
  post_build:
    commands:
       - echo "Revisando si existe el directorio de reporte..."
       - |
        if [ -d "allure-report" ]; then
        echo "Subiendo reporte a S3...";
        aws s3 sync allure-report s3://test-report-cypress-nazareth/ --region us-east-2;
        else
        echo "No se generó el directorio allure-report, no se subirá nada.";
        fi